"""adding card_bills table

Revision ID: 6887b67ecdfc
Revises: e3695adb6c2d
Create Date: 2023-03-16 00:46:06.765418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6887b67ecdfc'
down_revision = 'e3695adb6c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_bills',
    sa.Column('close_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('close_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_bills')
    # ### end Alembic commands ###
