"""First commit

Revision ID: e3695adb6c2d
Revises: 
Create Date: 2023-03-13 19:29:51.308149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3695adb6c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('payment_type', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.Column('charge_amount', sa.Integer(), nullable=True),
    sa.Column('remaining_charges', sa.Integer(), nullable=True),
    sa.Column('refund', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_transactions')
    op.drop_table('account_transactions')
    # ### end Alembic commands ###
